Experimental: qos api
artek-koltun/opi-api pull request #1
Opened 2023-04-11 06:53 UTC by artek-koltun

2023-04-11 17:00 UTC, benlwalker requested changes

2023-04-11 17:00 UTC, benlwalker commented on storage/v1alpha1/middleend_qos_device.proto
> +
The middleend has no concept of "devices" - it's just a stack of volumes. You can further see that this device object is associated with a frontend device, not a middleend/backend volume. So this is definitely not a middleend API you've defined. It's a frontend API.

It's also likely impossible to independently enable/disable encryption on a frontend device - it almost certainly has to be done as the frontend device is created. I'm also not convinced that frontend encryption will really work universally the same across all frontends.

Instead, I think you should define your QoSLimit message in the common file like you have, then embed that into the various frontend CreateDevice calls where it makes sense to do so.

2023-04-12 14:14 UTC, artek-koltun commented on storage/v1alpha1/middleend_qos_device.proto
> +
Updated

2023-04-12 16:03 UTC, benlwalker commented on storage/v1alpha1/frontend_virtio_blk.proto
> +
virtio-blk has a 1:1 mapping between the PCI endpoints and the block storage volumes. In other words, a virtio-blk controller only supports one namespace. That means the middle-end QoS is always sufficient and this isn't strictly needed. But I could be convinced to keep it for consistency.

2023-04-12 16:03 UTC, benlwalker approved these changes

2023-04-14 06:47 UTC, closed without merging